source_set("sqlite") {
    sources = [
        "SqliteCoverRepository.cpp",
        "SqliteSwitchRepository.cpp",
        "SqliteEndpointIdGenerator.cpp",
    ]

    public = [
        "SqliteCoverRepository.h",
        "SqliteSwitchRepository.h",
        "SqliteEndpointIdGenerator.h",
    ]

    deps = [ "//src/application" ]

    public_deps = [ "//src/common/persistence/sqlite" ]

    configs += [ "//:app_includes" ]
}
