source_set("mobilus") {
  sources = [ "MqttMobilusDeviceControlServiceTest.cpp" ]

  deps = [
    "//src/application",
    "//src/common/logging",
    "//src/driven_adapters/mobilus:device_control",
    "//tests/mobilus:mock_client",
    "//third_party/googletest:gmock",
    "//third_party/googletest:gtest",
  ]

  configs += [ "//tests:tests_include" ]
}
