#pragma once

#define CHIP_DEVICE_CONFIG_DYNAMIC_ENDPOINT_COUNT 100

#define CHIP_DEVICE_CONFIG_ENABLE_EXTENDED_DISCOVERY 1

#define CHIP_DEVICE_CONFIG_ENABLE_COMMISSIONABLE_DEVICE_TYPE 1

#define CHIP_DEVICE_CONFIG_ENABLE_COMMISSIONABLE_DEVICE_NAME 1

#define CHIP_DEVICE_CONFIG_ENABLE_PAIRING_AUTOSTART 1

#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_ID 0xFFF1

#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_NAME "Mobilus"

#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_ID 0x2001

#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_NAME "Cosmo GTW"

#define CHIP_DEVICE_CONFIG_DEVICE_TYPE 0x000E

#define CHIP_DEVICE_CONFIG_DEVICE_NAME "Mobilus Cosmo GTW"

#define CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION 501 // PHP_VERSION_ID convention: major * 1000 + minor * 100 + patch

#define CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING "0.5.1"

#define CHIP_DEVICE_CONFIG_DEVICE_HARDWARE_VERSION 1

#define CHIP_DEVICE_CONFIG_DEVICE_HARDWARE_VERSION_STRING "1.0"

#define CHIP_DEVICE_CONFIG_DEVICE_SETUP_PASSCODE 20202021

#define CHIP_DEVICE_CONFIG_DEVICE_SETUP_DISCRIMINATOR 2332

#ifdef __mips__
#define CHIP_STORAGE_DIR "/opt/jungi/var"
#else
#define CHIP_STORAGE_DIR "/tmp"
#endif

#define FATCONFDIR CHIP_STORAGE_DIR

#define SYSCONFDIR CHIP_STORAGE_DIR

#define LOCALSTATEDIR CHIP_STORAGE_DIR

#define CHIP_CONFIG_KVS_PATH "/dev/null" // unused, replaced by SQLite KVS impl

// include the CHIPProjectConfig from config/standalone
#include <CHIPProjectConfig.h>
