#!/bin/sh
set -e

CONF=$RUNTIME_DIR/etc/mobmatter.conf

echo "Enabling service"
/etc/init.d/mobmatter enable || true

echo "Adjust $CONF and /etc/init.d/mobmatter start"
echo "View logs via logread -e matter"

exit 0
