import("//build_overrides/chip.gni")

source_set("switch_cluster") {
  sources = [
    "SwitchAttributeAccess.cpp",
    "SwitchClusterAdapter.cpp",
    "SwitchCommandHandler.cpp",
    "SwitchBasicInfoLoader.cpp",
  ]

  public = [
    "SwitchAttributeAccess.h",
    "SwitchClusterAdapter.h",
    "SwitchCommandHandler.h",
    "SwitchBasicInfoLoader.h",
  ]

  deps = [
    "${chip_root}/src/app",
    "//src/application",
    "//src/driving_adapters/matter/bridged_device_cluster",
  ]

  configs += [ "//:app_includes" ]
}
